Select * from customer;

--Q1.   What is the total number of entries in the dataset?
Select count(*) as Total_Entries from customer;

--Q2. What is the total revenue generated by female and male customers?
Select "Gender", Sum("Purchase Amount (USD)") as Revenue from customer group by "Gender";

--Q3.Which customer used a discount but still spend more than the avearge amount?
SELECT "Customer ID","Purchase Amount (USD)" from customer where "Discount Applied"='Yes' AND "Purchase Amount (USD)">(SELECT AVG("Purchase Amount (USD)") FROM customer) ;

--Q4. Which are the top 5 product with the highest review rating?
SELECT "Item Purchased", ROUND(AVG("Review Rating")::numeric, 2) AS avg_rating FROM customer WHERE "Review Rating" IS NOT NULL GROUP BY "Item Purchased" ORDER BY avg_rating DESC LIMIT 5;

--Q5.Compare the average shippping amount between standard and express shipping?
SELECT Round(avg("Purchase Amount (USD)"), 2),"Shipping Type" from customer 
where "Shipping Type" in ('Express', 'Standard' ) group by "Shipping Type";

--Q6.Categorize customers into New, Loyal and Returning on their total number of previous 
--purchases, and show the count of each category.
WITH customer_type AS (
    SELECT
        "Customer ID",
        "Previous Purchases",
        CASE
            WHEN "Previous Purchases" = 1 THEN 'New'
            WHEN "Previous Purchases" BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)

SELECT
    customer_segment,
    COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment
ORDER BY "Number of Customers" DESC;

--Q7.What is the contribution of each age group?

